version: '3.8'

services:
 recycling:
  build:
   context: .
  ports:
   - 3000:3000
  environment:
   - PORT=3000
   - MONGO_URI=mongodb://mongo:27017/recycling_development
   - MEMCACHE_SERVERS=memcached:11211
  volumes:
   - ./:/app
   - /app/node_modules
  command: node server.js

 mongo:
  image: mongo:7.0.0
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb

 memcached:
  image: memcached:1.6.14

volumes:
 mongodb:
 mongodb_config: